# Generated by Django 4.0.1 on 2022-02-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_contributors_alter_blog_author'),
        ('blog', '0005_auto_20210428_0000'),
    ]

    operations = [
    ]
