# Generated by Django 4.0.2 on 2022-02-05 12:46

from django.db import migrations


def create_groups(apps, schema_migration):
    User = apps.get_model("authentication", "User")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    add_photo = Permission.objects.get(codename="add_photo")
    change_photo = Permission.objects.get(codename="change_photo")
    delete_photo = Permission.objects.get(codename="delete_photo")
    view_photo = Permission.objects.get(codename="view_photo")

    add_multiple_photos = Permission.objects.get(codename="create_multiple_photos")

    create_blog = Permission.objects.get(codename="create_blog")
    edit_blog = Permission.objects.get(codename="edit_blog")

    creator_permissions = [
        add_photo,
        change_photo,
        delete_photo,
        view_photo,
        add_multiple_photos,
        create_blog,
        edit_blog,
    ]

    creators = Group(name="creators")
    creators.save()

    creators.permissions.set(creator_permissions)

    subscribers = Group(name="subscribers")
    subscribers.save()

    subscribers.permissions.add(view_photo)

    for user in User.objects.all():
        if user.role == "CREATOR":
            creators.user_set.add(user)
        if user.role == "SUBSCRIBER":
            subscribers.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_profile_photo_alter_user_role"),
    ]

    operations = [migrations.RunPython(create_groups)]
